# using image from https://gitlab.com/python-devs/ci-images/-/tree/main
image: registry.gitlab.com/python-devs/ci-images:active

stages:
  - build
  - tests
  - deploy

create docs:
  stage: build
  script:
    - pip --quiet install tox
    - tox -e docs
  artifacts:
    paths:
    - build

test:
  stage: tests
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
  script: 
    - pip --quiet install tox
    - tox
  artifacts:
    reports:
     cobertura: 'coverage.xml'

deploy docs:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script:
    - aws --version
    - aws s3 sync build/ s3://$AWS_S3_BUCKET/bandsaw/ --size-only
  only:
    - docs-deployment

pypi:
  stage: deploy
  only:
    - tags
  script:
    - pip --quiet install flit
    - flit publish --repository pypitest
