# using image from https://gitlab.com/python-devs/ci-images/-/tree/main
image: registry.gitlab.com/python-devs/ci-images:active

stages:
  - build
  - tests
  - deploy

build docs:
  stage: build
  script:
    - git config --local --add safe.directory /builds/kantai/bandsaw
    - pip --quiet install tox
    - tox -e docs

test:
  stage: tests
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
  script:
    - pip --quiet install tox
    - tox
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

pypi:
  stage: deploy
  image: python
  only:
    - tags
  script:
    - pip --quiet install flit
    - flit publish
